server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-productos
          uri: lb://service-productos
          predicates:
            - Path=/productos/**

        - id: service-usuario
          uri: lb://service-usuario
          predicates:
            - Path=/user/**